/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 5.7 */
/* Tue Jan 29 15:29:16 2019 */

/* parameterized module instance */
PLL_100MHz __ (.CLKI( ), .CLKOP( ));
