# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/1.work_user/1.noise_gen/noise_LCG/noise_LCG.srcs/sources_1/ip/mult_a_x/mult_a_x.xci
# IP: The module: 'mult_a_x' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/1.work_user/1.noise_gen/noise_LCG/noise_LCG.srcs/sources_1/ip/mult_a_x/mult_a_x_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_a_x'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/1.work_user/1.noise_gen/noise_LCG/noise_LCG.srcs/sources_1/ip/mult_a_x/mult_a_x.xci
# IP: The module: 'mult_a_x' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/1.work_user/1.noise_gen/noise_LCG/noise_LCG.srcs/sources_1/ip/mult_a_x/mult_a_x_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_a_x'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
